export const backofficeRoutes= [
  {
    id:1,
    name:'Novedades',
    route:'/backoffice/news'
  },
  {
    id:2,
    name:'Categorías',
    route:'/backoffice/categories'
  },
  {
    id:3,
    name:'Actividades',
    route:'/backoffice/activities'
  },
  {
    id:4,
    name:'Testimonios',
    route:'/backoffice/testimonials',    
  },
  {
    id:5,
    name:'Slides',
    route:'/backoffice/slides',    
  },
  {
    id:6,
    name:'Usuarios',
    route:'/backoffice/users'
  },
  {
    id:7,
    name:'Organización',
    route:'/backoffice/organization'
  },
  {
    id:8,
    name:'Miembros',
    route:'/backoffice/members'
  }
]